### PR TITLE
IT-3492: Remove resource name

### PR DESCRIPTION
**Pull request by xschildw**

### CODE REVIEW

**Review by thomasyu888 — APPROVED** [review]
thanks!  I'll approve, but I'll wait for Joni for their feedback

**Review by ConsoleCatzirl — COMMENTED** [review]
I think this will resolve the deploy error, but I'm not sure if it will also disrupt any currently-running jobs.

**Comment by xschildw** [comment]
If the update causes a resource replacement, I would expect it to cancel running jobs. Did we use the name to prevent that from happening?

**Comment by thomasyu888** [comment]
> If the update causes a resource replacement, I would expect it to cancel running jobs. Did we use the name to prevent that from happening?

@xschildw , @jesusaurus not sure, but see this thread with @zaro0508 and I : https://sagebionetworks.slack.com/archives/CEFQD0KU1/p1707431159671579?thread_ts=1707179392.118219&cid=CEFQD0KU1.

**Review by ConsoleCatzirl — APPROVED** [review]

**Review by zaro0508 — CHANGES_REQUESTED** [review]
DONT DO THIS!

**Pull request closed without merging**
